### PR TITLE
Use the new mods update DSA endpoint for saving MODS

### LINKED ISSUE #828: Switch Accession:DescriptiveMetadata to use update mods endpoint
Instead of legacy_update endpoint.

See https://github.com/sul-dlss/dor-services-app/issues/3282 for creating that endpoint.

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?
Fixes #828

### CODE REVIEW

**Review by justinlittman — APPROVED** [review]

**Comment by jcoyne** [comment]
@justinlittman I'm not sure I know how to exercise this in the "real world". Maybe @andrewjbtw  knows.

**Comment by justinlittman** [comment]
Is there an integration test that hits this? Otherwise, testing the change for https://github.com/sul-dlss/argo/pull/3064 is close enough. (I just don't want to be surprised during dependency updates on Monday.)

**Comment by jcoyne** [comment]
I don't believe there is an integration test for this.

**Comment by andrewjbtw** [comment]
I did a very basic update but it looks like it worked: https://argo-stage.stanford.edu/view/druid:bj416cv1812

I put the descMetadata.xml on `/dor/workspace/bj/416/cv/1812/bj416cv1812/metadata` and it got picked up in the accessionWF.

**Comment by jcoyne** [comment]
@andrewjbtw that's great, but I don't think we have this code deployed now. We should repeat this test next week.

**Comment by andrewjbtw** [comment]
No problem. I thought it was up based on this morning's discussion but hadn't checked if it was still up. It's not hard to repeat the test.

**Pull request merged**
