### PR TITLE
Remove the integration_tests

### PR DESCRIPTION
**Pull request by jcoyne**
These tests are never run in CI because the have dependencies on external servers.
We don't have an environment where we can run these.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Your thoughts on this, @cbeer 	@peetucket @SaravShah @atz 	?

**Comment by jcoyne** [comment]
I'll also note that this make upgrading dor-services easier because we can drop the dependency on `assembly-utils`

**Comment by SaravShah** [comment]
i'll let peter, chris, or joe respond. I've only touched this code base from updating dependencies :)

**Comment by peetucket** [comment]
Don’t have a strong opinion either way. Coverage is pretty bad according to coveralls (and this doesn’t change it).

**Comment by cbeer** [comment]
🤷‍♂️

**Pull request merged**
