### PR TITLE
Change compute checksums to digest in single pass.

### PR DESCRIPTION
**Pull request by justinlittman**
refs #1074

## Why was this change made? 🤔
Need for speed.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Unit

### CODE REVIEW

**Review by lwrubel — APPROVED** [review]

**Comment by mjgiarlo** [comment]
@justinlittman do you think we should consider extracting this to the assembly-objectfile gem too? Maybe it's worthy of a new method in the public interface of the gem. (Definitely backloggable if so.)

**Review by ndushay — COMMENTED** [review]
wow - this was a huge oversight.

**Comment by ndushay** [comment]
> @justinlittman do you think we should consider extracting this to the assembly-objectfile gem too? Maybe it's worthy of a new method in the public interface of the gem. (Definitely backloggable if so.)

the main advantage would be computing the two flavors of checksum at the same time if both were desired:  https://github.com/sul-dlss/assembly-objectfile/blob/main/lib/assembly/object_file.rb#L89-L98

It might also be worth figuring out if checksums are actually being computed with the gem.  https://github.com/sul-dlss/assembly-objectfile/network/dependents

**Comment by mjgiarlo** [comment]
@ndushay 💬 
> It might also be worth figuring out if checksums are actually being computed with the gem. [sul-dlss/assembly-objectfile (dependents)](https://github.com/sul-dlss/assembly-objectfile/network/dependents)

Good call. it could be the spot in common-accessioning that was already optimized for speed using inline code is the only spot where we care about such an optimization, so the extraction could be a chunk of work without much payoff.

**Pull request merged**
